---
- name: Install packages
  hosts: localhost
  tasks:
      - name: Run Pacman
        become: true
        pacman:
            name: "{{ item }}"
            state: present
        with_items:
            - awesome
            - chromium
            - firefox
            - fzf
            - neovim
            - i3lock
            - maim
            - openssh
            - termite
            - the_silver_searcher
            - ttf-hack
            - zsh

- name: Create symbolic links
  hosts: localhost 
  tasks:
        - name: Create neovim config directory
          file:
            path: "{{ ansible_env.HOME }}/.config/nvim/bundle"
            state: directory
        - name: Linking files
          file: 
            src: "{{ playbook_dir }}/home/{{ item }}"
            dest: "{{ ansible_env.HOME }}/{{ item }}"
            state: link
          with_items:
            - .config/awesome
            - .config/termite
            - .config/base16-shell
            - .config/nvim/init.vim
            - .config/nvim/bundle/Vundle.vim
            - .local/bin/lock
            - .local/bin/telegram
            - .local/bin/riot
            - .agignore
            - .env
            - .lynxrc
            - .padlock.png
            - .oh-my-zsh
            - .zsh_aliases
            - .zshrc

